Jakub\SymfonyBundle\Entity\Article:
    repositoryClass: Jakub\SymfonyBundle\Repository\ArticleRepository
    type: entity
    table: article
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        date:
            type: datetime
            nullable: false
            comment: ''
            default: ''
        type:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
    lifecycleCallbacks: {  }